/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.ysknmt.misc.codescanning;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
    public Integer getInteger() {
        Integer INTEGER_INVALID_NAME = new Integer(1);
        return INTEGER_INVALID_NAME;
    }
}
